from PySide6.QtCore import QSize, Qt
from PySide6.QtGui import QFont
from PySide6.QtWidgets import (QWidget, QGridLayout, QHBoxLayout, QLabel, QComboBox, QFrame, QVBoxLayout, QSpinBox,
    QDoubleSpinBox, QPushButton, QSpacerItem, QSizePolicy, QLineEdit, QCheckBox, QListWidget, QGroupBox,
    QAbstractSpinBox, QTreeWidget, QTreeWidgetItem)


class InvoicePage:
    def __init__(self):
        self.font8 = QFont()
        self.font8.setPointSize(14)
        self.font8.setBold(True)

    def initUi_InvoiceForm(self):
        self._p_factures = QWidget()
        self._p_factures.setObjectName(u"_p_factures")
        self._g_factures = QGridLayout(self._p_factures)
        self._g_factures.setSpacing(5)
        self._g_factures.setObjectName(u"_g_factures")
        self._g_factures.setContentsMargins(8, 0, 8, 10)
        self._h_invoice_search_invoice = QHBoxLayout()
        self._h_invoice_search_invoice.setObjectName(u"_h_invoice_search_invoice")
        self._l_invoice_search_invoice = QLabel(self._p_factures)
        self._l_invoice_search_invoice.setObjectName(u"_l_invoice_search_invoice")
        self._l_invoice_search_invoice.setMaximumSize(QSize(130, 16777215))
        self._h_invoice_search_invoice.addWidget(self._l_invoice_search_invoice)
        self._cbx_invoice_search_invoice = QComboBox(self._p_factures)
        self._cbx_invoice_search_invoice.setObjectName(u"_cbx_invoice_search_invoice")
        self._cbx_invoice_search_invoice.setMinimumSize(QSize(0, 30))
        self._cbx_invoice_search_invoice.setMaximumSize(QSize(16777215, 16777215))
        self._h_invoice_search_invoice.addWidget(self._cbx_invoice_search_invoice)
        self._g_factures.addLayout(self._h_invoice_search_invoice, 0, 1, 1, 2)
        self._f_invoice_input_card = QFrame(self._p_factures)
        self._f_invoice_input_card.setObjectName(u"_f_invoice_input_card")
        self._f_invoice_input_card.setMinimumSize(QSize(450, 0))
        self._f_invoice_input_card.setFrameShape(QFrame.Shape.StyledPanel)
        self._f_invoice_input_card.setFrameShadow(QFrame.Shadow.Raised)
        self._v_input_card = QVBoxLayout(self._f_invoice_input_card)
        self._v_input_card.setObjectName(u"_v_input_card")
        self._v_input_card.setContentsMargins(10, 10, 10, 10)
        self._f_invoice_informations_article_label = QFrame(self._f_invoice_input_card)
        self._f_invoice_informations_article_label.setObjectName(u"_f_invoice_informations_article_label")
        self._f_invoice_informations_article_label.setMinimumSize(QSize(0, 30))
        self._f_invoice_informations_article_label.setMaximumSize(QSize(16777215, 30))
        self._f_invoice_informations_article_label.setFrameShape(QFrame.Shape.StyledPanel)
        self._f_invoice_informations_article_label.setFrameShadow(QFrame.Shadow.Raised)
        self._h_invoice_informations_article_label = QHBoxLayout(self._f_invoice_informations_article_label)
        self._h_invoice_informations_article_label.setObjectName(u"_h_invoice_informations_article_label")
        self._h_invoice_informations_article_label.setContentsMargins(5, 0, 5, 0)
        self._l_invoice_informations_article = QLabel(self._f_invoice_informations_article_label)
        self._l_invoice_informations_article.setObjectName(u"_l_invoice_informations_article")
        self._l_invoice_informations_article.setFont(self.font3)
        self._l_invoice_informations_article.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._h_invoice_informations_article_label.addWidget(self._l_invoice_informations_article)
        self._v_input_card.addWidget(self._f_invoice_informations_article_label)
        self._g_invoice_input_card = QGridLayout()
        self._g_invoice_input_card.setObjectName(u"_g_invoice_input_card")
        self._s_invoice_quantity = QSpinBox(self._f_invoice_input_card)
        self._s_invoice_quantity.setObjectName(u"_s_invoice_quantity")
        self._s_invoice_quantity.setMinimumSize(QSize(0, 30))
        self._s_invoice_quantity.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._s_invoice_quantity, 7, 0, 1, 1)
        self._ds_invoice_remise = QDoubleSpinBox(self._f_invoice_input_card)
        self._ds_invoice_remise.setObjectName(u"_ds_invoice_remise")
        self._ds_invoice_remise.setMinimumSize(QSize(0, 30))
        self._ds_invoice_remise.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._ds_invoice_remise, 12, 0, 1, 1)
        self._l_invoice_type_remise = QLabel(self._f_invoice_input_card)
        self._l_invoice_type_remise.setObjectName(u"_l_invoice_type_remise")
        self._l_invoice_type_remise.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._l_invoice_type_remise, 9, 0, 1, 1)
        self._l_invoice_remise = QLabel(self._f_invoice_input_card)
        self._l_invoice_remise.setObjectName(u"_l_invoice_remise")
        self._l_invoice_remise.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._l_invoice_remise, 11, 0, 1, 1)
        self._cbx_invoice_type_remise = QComboBox(self._f_invoice_input_card)
        self._cbx_invoice_type_remise.addItem(self.euro_icon, "")
        self._cbx_invoice_type_remise.addItem(self.pourcentage_icon, "")
        self._cbx_invoice_type_remise.setObjectName(u"_cbx_invoice_type_remise")
        self._cbx_invoice_type_remise.setMinimumSize(QSize(0, 30))
        self._cbx_invoice_type_remise.setEditable(False)
        self._g_invoice_input_card.addWidget(self._cbx_invoice_type_remise, 10, 0, 1, 1)
        self._l_invoice_nom = QLabel(self._f_invoice_input_card)
        self._l_invoice_nom.setObjectName(u"_l_invoice_nom")
        self._l_invoice_nom.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._l_invoice_nom, 0, 0, 1, 1)
        self._l_invoice_qauntity = QLabel(self._f_invoice_input_card)
        self._l_invoice_qauntity.setObjectName(u"_l_invoice_qauntity")
        self._l_invoice_qauntity.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._l_invoice_qauntity, 6, 0, 1, 1)
        self._h_btn_invoice_input = QHBoxLayout()
        self._h_btn_invoice_input.setObjectName(u"_h_btn_invoice_input")
        self._b_invoice_cancel_card = QPushButton(self._f_invoice_input_card)
        self._b_invoice_cancel_card.setObjectName(u"_b_invoice_cancel_card")
        self._b_invoice_cancel_card.setMinimumSize(QSize(120, 40))
        self._b_invoice_cancel_card.setIcon(self.annuler_icon)
        self._b_invoice_cancel_card.setIconSize(QSize(25, 25))
        self._b_invoice_cancel_card.setFlat(True)
        self._h_btn_invoice_input.addWidget(self._b_invoice_cancel_card)
        self._hs_btn_invoice_input = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self._h_btn_invoice_input.addItem(self._hs_btn_invoice_input)
        self._b_invoice_add_card = QPushButton(self._f_invoice_input_card)
        self._b_invoice_add_card.setObjectName(u"_b_invoice_add_card")
        self._b_invoice_add_card.setMinimumSize(QSize(180, 40))
        self._b_invoice_add_card.setFont(self.font3)
        self._b_invoice_add_card.setIcon(self.commande_icon)
        self._b_invoice_add_card.setIconSize(QSize(25, 25))
        self._b_invoice_add_card.setFlat(True)
        self._h_btn_invoice_input.addWidget(self._b_invoice_add_card)
        self._g_invoice_input_card.addLayout(self._h_btn_invoice_input, 13, 0, 1, 1)
        self._ds_invoice_price = QDoubleSpinBox(self._f_invoice_input_card)
        self._ds_invoice_price.setObjectName(u"_ds_invoice_price")
        self._ds_invoice_price.setMinimumSize(QSize(0, 30))
        self._ds_invoice_price.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._ds_invoice_price, 5, 0, 1, 1)
        self._le_invoice_marque = QLineEdit(self._f_invoice_input_card)
        self._le_invoice_marque.setObjectName(u"_le_invoice_marque")
        self._le_invoice_marque.setMinimumSize(QSize(0, 30))
        self._le_invoice_marque.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._le_invoice_marque, 3, 0, 1, 1)
        self._le_invoice_name = QLineEdit(self._f_invoice_input_card)
        self._le_invoice_name.setObjectName(u"_le_invoice_name")
        self._le_invoice_name.setMinimumSize(QSize(0, 30))
        self._le_invoice_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._le_invoice_name, 1, 0, 1, 1)
        self._l_invoice_price = QLabel(self._f_invoice_input_card)
        self._l_invoice_price.setObjectName(u"_l_invoice_price")
        self._l_invoice_price.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._l_invoice_price, 4, 0, 1, 1)
        self._l_invoice_marque = QLabel(self._f_invoice_input_card)
        self._l_invoice_marque.setObjectName(u"_l_invoice_marque")
        self._l_invoice_marque.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_input_card.addWidget(self._l_invoice_marque, 2, 0, 1, 1)
        self._h_invoice_info_qty = QHBoxLayout()
        self._h_invoice_info_qty.setObjectName(u"_h_invoice_info_qty")
        self._cb_invoice_quantifiable = QCheckBox(self._f_invoice_input_card)
        self._cb_invoice_quantifiable.setObjectName(u"_cb_invoice_quantifiable")
        self._h_invoice_info_qty.addWidget(self._cb_invoice_quantifiable)
        self._cb_invoice_location = QCheckBox(self._f_invoice_input_card)
        self._cb_invoice_location.setObjectName(u"_cb_invoice_location")
        self._h_invoice_info_qty.addWidget(self._cb_invoice_location)
        self._g_invoice_input_card.addLayout(self._h_invoice_info_qty, 8, 0, 1, 1)
        self._v_input_card.addLayout(self._g_invoice_input_card)
        self._lw_list_card = QListWidget(self._f_invoice_input_card)
        self._lw_list_card.setObjectName(u"_lw_list_card")
        self._v_input_card.addWidget(self._lw_list_card)
        self._g_factures.addWidget(self._f_invoice_input_card, 1, 1, 2, 1)
        self._f_invoice_box_export_invoice = QFrame(self._p_factures)
        self._f_invoice_box_export_invoice.setObjectName(u"_f_invoice_box_export_invoice")
        self._f_invoice_box_export_invoice.setMaximumSize(QSize(400, 16777215))
        self._f_invoice_box_export_invoice.setFrameShape(QFrame.Shape.StyledPanel)
        self._f_invoice_box_export_invoice.setFrameShadow(QFrame.Shadow.Raised)
        self._g_box_export_invoice = QGridLayout(self._f_invoice_box_export_invoice)
        self._g_box_export_invoice.setObjectName(u"_g_box_export_invoice")
        self._g_box_export_invoice.setContentsMargins(5, 10, 5, 10)
        self._v_incoice_client_combo = QVBoxLayout()
        self._v_incoice_client_combo.setSpacing(-1)
        self._v_incoice_client_combo.setObjectName(u"_v_incoice_client_combo")
        self._v_incoice_client_combo.setContentsMargins(-1, -1, -1, 5)
        self._l_invoice_client = QLabel(self._f_invoice_box_export_invoice)
        self._l_invoice_client.setObjectName(u"_l_invoice_client")
        self._l_invoice_client.setMaximumSize(QSize(16777215, 20))
        self._v_incoice_client_combo.addWidget(self._l_invoice_client)
        self._cbx_invoice_client = QComboBox(self._f_invoice_box_export_invoice)
        self._cbx_invoice_client.setObjectName(u"_cbx_invoice_client")
        self._cbx_invoice_client.setMinimumSize(QSize(0, 30))
        self._v_incoice_client_combo.addWidget(self._cbx_invoice_client)
        self._f_invoice_warning_client = QFrame(self._f_invoice_box_export_invoice)
        self._f_invoice_warning_client.setObjectName(u"_f_invoice_warning_client")
        self._f_invoice_warning_client.setFrameShape(QFrame.Shape.StyledPanel)
        self._f_invoice_warning_client.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self._f_invoice_warning_client)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self._l_invoice_warning_message = QLabel(self._f_invoice_warning_client)
        self._l_invoice_warning_message.setObjectName(u"_l_invoice_warning_message")
        self.horizontalLayout.addWidget(self._l_invoice_warning_message)
        self._v_incoice_client_combo.addWidget(self._f_invoice_warning_client)
        self._g_box_export_invoice.addLayout(self._v_incoice_client_combo, 0, 0, 1, 2)
        self._gb_invoice_info_client = QGroupBox(self._f_invoice_box_export_invoice)
        self._gb_invoice_info_client.setObjectName(u"_gb_invoice_info_client")
        self._gb_invoice_info_client.setFont(self.font3)
        self._gb_invoice_info_client.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._gb_invoice_info_client.setFlat(True)
        self._v_invoice_info_client = QVBoxLayout(self._gb_invoice_info_client)
        self._v_invoice_info_client.setObjectName(u"_v_invoice_info_client")
        self._v_invoice_info_client.setContentsMargins(5, 5, 5, 5)
        self._l_invoice_nomclient = QLabel(self._gb_invoice_info_client)
        self._l_invoice_nomclient.setObjectName(u"_l_invoice_nomclient")
        self._v_invoice_info_client.addWidget(self._l_invoice_nomclient)
        self._le_invoice_nomclient = QLineEdit(self._gb_invoice_info_client)
        self._le_invoice_nomclient.setObjectName(u"_le_invoice_nomclient")
        self._le_invoice_nomclient.setMinimumSize(QSize(0, 25))
        self._v_invoice_info_client.addWidget(self._le_invoice_nomclient)
        self._l_invoice_numclient = QLabel(self._gb_invoice_info_client)
        self._l_invoice_numclient.setObjectName(u"_l_invoice_numclient")
        self._v_invoice_info_client.addWidget(self._l_invoice_numclient)
        self._le_invoice_numclient = QLineEdit(self._gb_invoice_info_client)
        self._le_invoice_numclient.setObjectName(u"_le_invoice_numclient")
        self._le_invoice_numclient.setMinimumSize(QSize(0, 25))
        self._v_invoice_info_client.addWidget(self._le_invoice_numclient)
        self._l_invoice_mailclient = QLabel(self._gb_invoice_info_client)
        self._l_invoice_mailclient.setObjectName(u"_l_invoice_mailclient")
        self._v_invoice_info_client.addWidget(self._l_invoice_mailclient)
        self._le_invoice_mailclient = QLineEdit(self._gb_invoice_info_client)
        self._le_invoice_mailclient.setObjectName(u"_le_invoice_mailclient")
        self._le_invoice_mailclient.setMinimumSize(QSize(0, 25))
        self._v_invoice_info_client.addWidget(self._le_invoice_mailclient)
        self._g_box_export_invoice.addWidget(self._gb_invoice_info_client, 1, 0, 1, 2)
        self._l_invoice_total = QLabel(self._f_invoice_box_export_invoice)
        self._l_invoice_total.setObjectName(u"_l_invoice_total")
        self._l_invoice_total.setFont(self.font8)
        self._l_invoice_total.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self._g_box_export_invoice.addWidget(self._l_invoice_total, 7, 0, 1, 1)
        self._b_invoice_export = QPushButton(self._f_invoice_box_export_invoice)
        self._b_invoice_export.setObjectName(u"_b_invoice_export")
        self._b_invoice_export.setMinimumSize(QSize(0, 25))
        self._b_invoice_export.setFont(self.font3)
        self._g_box_export_invoice.addWidget(self._b_invoice_export, 9, 1, 1, 1)
        self._ds_invoice_total_remise = QDoubleSpinBox(self._f_invoice_box_export_invoice)
        self._ds_invoice_total_remise.setObjectName(u"_ds_invoice_total_remise")
        self._ds_invoice_total_remise.setFrame(True)
        self._ds_invoice_total_remise.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self._ds_invoice_total_remise.setMaximum(100000000000000004764729344.000000000000000)
        self._g_box_export_invoice.addWidget(self._ds_invoice_total_remise, 5, 1, 1, 1)
        self._hs_bottom_box_export_invoice = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self._g_box_export_invoice.addItem(self._hs_bottom_box_export_invoice, 9, 0, 1, 1)
        self._ds_invoice_total = QDoubleSpinBox(self._f_invoice_box_export_invoice)
        self._ds_invoice_total.setObjectName(u"_ds_invoice_total")
        self._ds_invoice_total.setMinimumSize(QSize(0, 25))
        self._ds_invoice_total.setFont(self.font3)
        self._ds_invoice_total.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self._ds_invoice_total.setReadOnly(True)
        self._ds_invoice_total.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self._ds_invoice_total.setMaximum(999999999999999.000000000000000)
        self._g_box_export_invoice.addWidget(self._ds_invoice_total, 7, 1, 1, 1)
        self._s_invoice_validity = QSpinBox(self._f_invoice_box_export_invoice)
        self._s_invoice_validity.setObjectName(u"_s_invoice_validity")
        self._s_invoice_validity.setMinimumSize(QSize(0, 25))
        self._s_invoice_validity.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self._s_invoice_validity.setMaximum(1000)
        self._s_invoice_validity.setValue(30)
        self._g_box_export_invoice.addWidget(self._s_invoice_validity, 6, 1, 1, 1)
        self._b_invoice_total_remise = QPushButton(self._f_invoice_box_export_invoice)
        self._b_invoice_total_remise.setObjectName(u"_b_invoice_total_remise")
        self._b_invoice_total_remise.setIcon(self.ajouter_icon)
        self._b_invoice_total_remise.setFlat(True)
        self._g_box_export_invoice.addWidget(self._b_invoice_total_remise, 5, 0, 1, 1)
        self._l_invoice_validity = QLabel(self._f_invoice_box_export_invoice)
        self._l_invoice_validity.setObjectName(u"_l_invoice_validity")
        self._l_invoice_validity.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self._g_box_export_invoice.addWidget(self._l_invoice_validity, 6, 0, 1, 1)
        self._gb_invoice_title = QGroupBox(self._f_invoice_box_export_invoice)
        self._gb_invoice_title.setObjectName(u"_gb_invoice_title")
        self._gb_invoice_title.setFont(self.font3)
        self._gb_invoice_title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._gb_invoice_title.setFlat(True)
        self._v_invoice_title = QVBoxLayout(self._gb_invoice_title)
        self._v_invoice_title.setObjectName(u"_v_invoice_title")
        self._v_invoice_title.setContentsMargins(5, 5, 5, 5)
        self._l_invoice_objet = QLabel(self._gb_invoice_title)
        self._l_invoice_objet.setObjectName(u"_l_invoice_objet")
        self._v_invoice_title.addWidget(self._l_invoice_objet)
        self._le_invoice_objet = QLineEdit(self._gb_invoice_title)
        self._le_invoice_objet.setObjectName(u"_le_invoice_objet")
        self._le_invoice_objet.setMinimumSize(QSize(0, 25))
        self._v_invoice_title.addWidget(self._le_invoice_objet)
        self._g_box_export_invoice.addWidget(self._gb_invoice_title, 2, 0, 1, 2)
        self._g_factures.addWidget(self._f_invoice_box_export_invoice, 1, 2, 1, 1)
        self._v_invoice_box_document = QVBoxLayout()
        self._v_invoice_box_document.setObjectName(u"_v_invoice_box_document")
        self._v_invoice_type_document = QVBoxLayout()
        self._v_invoice_type_document.setSpacing(1)
        self._v_invoice_type_document.setObjectName(u"_v_invoice_type_document")
        self._l_type_document = QLabel(self._p_factures)
        self._l_type_document.setObjectName(u"_l_type_document")
        self._l_type_document.setMaximumSize(QSize(400, 16777215))
        self._v_invoice_type_document.addWidget(self._l_type_document)
        self._cbx_invoice_type_document = QComboBox(self._p_factures)
        self._cbx_invoice_type_document.addItem(self.excel_icon, "")
        self._cbx_invoice_type_document.addItem(self.pdf_icon, "")
        self._cbx_invoice_type_document.setObjectName(u"_cbx_invoice_type_document")
        self._cbx_invoice_type_document.setMinimumSize(QSize(0, 30))
        self._cbx_invoice_type_document.setMaximumSize(QSize(400, 16777215))
        self._cbx_invoice_type_document.setEditable(False)
        self._v_invoice_type_document.addWidget(self._cbx_invoice_type_document)
        self._trw_invoice_export = QTreeWidget(self._p_factures)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self._trw_invoice_export.setHeaderItem(__qtreewidgetitem)
        self._trw_invoice_export.setObjectName(u"_trw_invoice_export")
        self._trw_invoice_export.setMaximumSize(QSize(400, 16777215))
        self._trw_invoice_export.setIndentation(15)
        self._trw_invoice_export.setAnimated(True)
        self._trw_invoice_export.setHeaderHidden(True)
        self._trw_invoice_export.header().setVisible(False)
        self._v_invoice_type_document.addWidget(self._trw_invoice_export)
        self._v_invoice_box_document.addLayout(self._v_invoice_type_document)
        self._g_factures.addLayout(self._v_invoice_box_document, 2, 2, 1, 1)
        self._f_invoice_inventory = QFrame(self._p_factures)
        self._f_invoice_inventory.setObjectName(u"_f_invoice_inventory")
        self._f_invoice_inventory.setMinimumSize(QSize(380, 0))
        self._f_invoice_inventory.setMaximumSize(QSize(380, 16777215))
        self._f_invoice_inventory.setFrameShape(QFrame.Shape.StyledPanel)
        self._f_invoice_inventory.setFrameShadow(QFrame.Shadow.Raised)
        self._v_invoice_inventory = QVBoxLayout(self._f_invoice_inventory)
        self._v_invoice_inventory.setObjectName(u"_v_invoice_inventory")
        self._v_invoice_inventory.setContentsMargins(5, 8, 5, 8)
        self._l_invoice_inventory_filter = QLabel(self._f_invoice_inventory)
        self._l_invoice_inventory_filter.setObjectName(u"_l_invoice_inventory_filter")
        self._v_invoice_inventory.addWidget(self._l_invoice_inventory_filter)
        self._le_invoice_inventory_filter = QLineEdit(self._f_invoice_inventory)
        self._le_invoice_inventory_filter.setObjectName(u"_le_invoice_inventory_filter")
        self._le_invoice_inventory_filter.setMinimumSize(QSize(0, 30))
        self._v_invoice_inventory.addWidget(self._le_invoice_inventory_filter)
        self._lw_invoice_list_inventory = QListWidget(self._f_invoice_inventory)
        self._lw_invoice_list_inventory.setObjectName(u"_lw_invoice_list_inventory")
        self._v_invoice_inventory.addWidget(self._lw_invoice_list_inventory)
        self._f_invoice_preview_card = QFrame(self._f_invoice_inventory)
        self._f_invoice_preview_card.setObjectName(u"_f_invoice_preview_card")
        self._f_invoice_preview_card.setFrameShape(QFrame.Shape.StyledPanel)
        self._f_invoice_preview_card.setFrameShadow(QFrame.Shadow.Raised)
        self._g_invoice_preview_card = QGridLayout(self._f_invoice_preview_card)
        self._g_invoice_preview_card.setSpacing(-1)
        self._g_invoice_preview_card.setObjectName(u"_g_invoice_preview_card")
        self._g_invoice_preview_card.setContentsMargins(0, 0, 0, 5)
        self._f_invoice_preview_inventory = QFrame(self._f_invoice_preview_card)
        self._f_invoice_preview_inventory.setObjectName(u"_f_invoice_preview_inventory")
        self._f_invoice_preview_inventory.setMaximumSize(QSize(16777215, 330))
        self._f_invoice_preview_inventory.setFrameShape(QFrame.Shape.StyledPanel)
        self._f_invoice_preview_inventory.setFrameShadow(QFrame.Shadow.Raised)
        self._g_invoice_preview_inventory = QGridLayout(self._f_invoice_preview_inventory)
        self._g_invoice_preview_inventory.setSpacing(-1)
        self._g_invoice_preview_inventory.setObjectName(u"_g_invoice_preview_inventory")
        self._g_invoice_preview_inventory.setContentsMargins(0, 0, 0, 0)
        self._l_invoice_preview_label_marque = QLabel(self._f_invoice_preview_inventory)
        self._l_invoice_preview_label_marque.setObjectName(u"_l_invoice_preview_label_marque")
        self._l_invoice_preview_label_marque.setMinimumSize(QSize(0, 20))
        self._l_invoice_preview_label_marque.setFont(self.font3)
        self._l_invoice_preview_label_marque.setAlignment(Qt.AlignmentFlag.AlignJustify|Qt.AlignmentFlag.AlignVCenter)
        self._g_invoice_preview_inventory.addWidget(self._l_invoice_preview_label_marque, 4, 0, 1, 1)
        self._l_invoice_preview = QLabel(self._f_invoice_preview_inventory)
        self._l_invoice_preview.setObjectName(u"_l_invoice_preview")
        self._l_invoice_preview.setMinimumSize(QSize(0, 250))
        self._g_invoice_preview_inventory.addWidget(self._l_invoice_preview, 0, 0, 1, 3)
        self._l_invoice_preview_label_name = QLabel(self._f_invoice_preview_inventory)
        self._l_invoice_preview_label_name.setObjectName(u"_l_invoice_preview_label_name")
        self._l_invoice_preview_label_name.setMinimumSize(QSize(0, 20))
        self._l_invoice_preview_label_name.setFont(self.font3)
        self._l_invoice_preview_label_name.setAlignment(Qt.AlignmentFlag.AlignJustify|Qt.AlignmentFlag.AlignVCenter)
        self._g_invoice_preview_inventory.addWidget(self._l_invoice_preview_label_name, 3, 0, 1, 1)
        self._l_invoice_preview_label_quantity = QLabel(self._f_invoice_preview_inventory)
        self._l_invoice_preview_label_quantity.setObjectName(u"_l_invoice_preview_label_quantity")
        self._l_invoice_preview_label_quantity.setMinimumSize(QSize(0, 20))
        self._l_invoice_preview_label_quantity.setFont(self.font3)
        self._l_invoice_preview_label_quantity.setAlignment(Qt.AlignmentFlag.AlignJustify|Qt.AlignmentFlag.AlignVCenter)
        self._g_invoice_preview_inventory.addWidget(self._l_invoice_preview_label_quantity, 5, 0, 1, 1)
        self._l_invoice_preview_quantity = QLabel(self._f_invoice_preview_inventory)
        self._l_invoice_preview_quantity.setObjectName(u"_l_invoice_preview_quantity")
        self._l_invoice_preview_quantity.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_preview_inventory.addWidget(self._l_invoice_preview_quantity, 5, 1, 1, 2)
        self._l_invoice_preview_marque = QLabel(self._f_invoice_preview_inventory)
        self._l_invoice_preview_marque.setObjectName(u"_l_invoice_preview_marque")
        self._l_invoice_preview_marque.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_preview_inventory.addWidget(self._l_invoice_preview_marque, 4, 1, 1, 2)
        self._l_invoice_preview_name = QLabel(self._f_invoice_preview_inventory)
        self._l_invoice_preview_name.setObjectName(u"_l_invoice_preview_name")
        self._l_invoice_preview_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_preview_inventory.addWidget(self._l_invoice_preview_name, 3, 1, 1, 2)
        self._g_invoice_preview_card.addWidget(self._f_invoice_preview_inventory, 0, 0, 1, 1)
        self._l_invoice_select_inventory = QLabel(self._f_invoice_preview_card)
        self._l_invoice_select_inventory.setObjectName(u"_l_invoice_select_inventory")
        self._l_invoice_select_inventory.setFont(self.font3)
        self._l_invoice_select_inventory.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._g_invoice_preview_card.addWidget(self._l_invoice_select_inventory, 1, 0, 1, 1)
        self._v_invoice_inventory.addWidget(self._f_invoice_preview_card)
        self._g_factures.addWidget(self._f_invoice_inventory, 0, 0, 3, 1)
        self._sw_main_dialog.addWidget(self._p_factures)
