from PySide6.QtCore import QSize, Qt
from PySide6.QtWidgets import (QWidget, QGridLayout, QFrame, QLabel, QHBoxLayout, QLineEdit, QPushButton, QListWidget,
    QVBoxLayout, QLayout, QDoubleSpinBox, QSpinBox, QCheckBox, QComboBox, QDateEdit, QToolButton)

from forms.gui import CustomCardWidget


class InventoryPage:
    def initUi_InventoryForm(self):
        self._p_inventory = QWidget()
        self._p_inventory.setObjectName(u"_p_inventory")
        self._g_inventory = QGridLayout(self._p_inventory)
        self._g_inventory.setObjectName(u"_g_inventory")
        self._g_inventory.setContentsMargins(8, 10, 10, 10)
        self._ccw_inventory_most_sale = CustomCardWidget([42, 157, 143, 1], self)
        self._ccw_inventory_most_sale.setObjectName(u"_ccw_inventory_most_sale")
        self._ccw_inventory_most_sale.setMinimumSize(QSize(0, 70))
        self._ccw_inventory_most_sale.setMaximumSize(QSize(16777215, 70))
        self._g_inventory_most_sale = QGridLayout(self._ccw_inventory_most_sale)
        self._g_inventory_most_sale.setObjectName(u"_g_inventory_most_sale")
        self._l_inventory_most_sale_value = QLabel(self._ccw_inventory_most_sale)
        self._l_inventory_most_sale_value.setObjectName(u"_l_inventory_most_sale_value")
        self._l_inventory_most_sale_value.setFont(self.font9)
        self._g_inventory_most_sale.addWidget(self._l_inventory_most_sale_value, 0, 1, 1, 1)
        self._l_inventory_most_sale = QLabel(self._ccw_inventory_most_sale)
        self._l_inventory_most_sale.setObjectName(u"_l_inventory_most_sale")
        self._g_inventory_most_sale.addWidget(self._l_inventory_most_sale, 1, 1, 1, 1)
        self._l_inventory_icon_most_sale = QLabel(self._ccw_inventory_most_sale)
        self._l_inventory_icon_most_sale.setObjectName(u"_l_inventory_icon_most_sale")
        self._l_inventory_icon_most_sale.setMinimumSize(QSize(45, 45))
        self._l_inventory_icon_most_sale.setMaximumSize(QSize(45, 45))
        self._l_inventory_icon_most_sale.setPixmap(self.plus_vendu_pixmap)
        self._l_inventory_icon_most_sale.setScaledContents(True)
        self._g_inventory_most_sale.addWidget(self._l_inventory_icon_most_sale, 0, 0, 2, 1)
        self._g_inventory.addWidget(self._ccw_inventory_most_sale, 2, 0, 1, 1)
        self._h_inventory_top = QHBoxLayout()
        self._h_inventory_top.setObjectName(u"_h_inventory_top")
        self._h_inventory_top.setContentsMargins(5, -1, 5, -1)
        self._f_inventory_sum_product = QFrame(self._p_inventory)
        self._f_inventory_sum_product.setObjectName(u"_f_inventory_sum_product")
        self._f_inventory_sum_product.setFrameShape(QFrame.Shape.StyledPanel)
        self._f_inventory_sum_product.setFrameShadow(QFrame.Shadow.Raised)
        self._h_inventory_sum_product = QHBoxLayout(self._f_inventory_sum_product)
        self._h_inventory_sum_product.setSpacing(1)
        self._h_inventory_sum_product.setObjectName(u"_h_inventory_sum_product")
        self._h_inventory_sum_product.setContentsMargins(2, 2, 2, 2)
        self._l_inventory_sum_value = QLabel(self._f_inventory_sum_product)
        self._l_inventory_sum_value.setObjectName(u"_l_inventory_sum_value")
        self._l_inventory_sum_value.setFont(self.font8)
        self._h_inventory_sum_product.addWidget(self._l_inventory_sum_value)
        self._l_inventory_sum = QLabel(self._f_inventory_sum_product)
        self._l_inventory_sum.setObjectName(u"_l_inventory_sum")
        self._h_inventory_sum_product.addWidget(self._l_inventory_sum)
        self._h_inventory_top.addWidget(self._f_inventory_sum_product)
        self._le_inventory_search_product = QLineEdit(self._p_inventory)
        self._le_inventory_search_product.setObjectName(u"_le_inventory_search_product")
        self._le_inventory_search_product.setMinimumSize(QSize(0, 30))
        self._h_inventory_top.addWidget(self._le_inventory_search_product)
        self._b_inventory_add_product = QPushButton(self._p_inventory)
        self._b_inventory_add_product.setObjectName(u"_b_inventory_add_product")
        self._b_inventory_add_product.setMinimumSize(QSize(0, 30))
        self._b_inventory_add_product.setIcon(self.plus_icon)
        self._h_inventory_top.addWidget(self._b_inventory_add_product)
        self._g_inventory.addLayout(self._h_inventory_top, 0, 0, 1, 4)
        self._lw_inventory_list_inventory = QListWidget(self._p_inventory)
        self._lw_inventory_list_inventory.setObjectName(u"_lw_inventory_list_inventory")
        self._g_inventory.addWidget(self._lw_inventory_list_inventory, 1, 0, 1, 3)
        self._f_inventory_box_edit = QFrame(self._p_inventory)
        self._f_inventory_box_edit.setObjectName(u"_f_inventory_box_edit")
        self._f_inventory_box_edit.setMaximumSize(QSize(450, 16777215))
        self._f_inventory_box_edit.setFrameShape(QFrame.Shape.StyledPanel)
        self._f_inventory_box_edit.setFrameShadow(QFrame.Shadow.Raised)
        self._v_inventory_box_edit = QVBoxLayout(self._f_inventory_box_edit)
        self._v_inventory_box_edit.setObjectName(u"_v_inventory_box_edit")
        self._v_inventory_box_edit.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self._v_inventory_box_edit.setContentsMargins(5, 5, 5, 5)
        self._f_inventory_informations_label = QFrame(self._f_inventory_box_edit)
        self._f_inventory_informations_label.setObjectName(u"_f_inventory_informations_label")
        self._f_inventory_informations_label.setMinimumSize(QSize(0, 40))
        self._f_inventory_informations_label.setMaximumSize(QSize(16777215, 40))
        self._f_inventory_informations_label.setFrameShape(QFrame.Shape.StyledPanel)
        self._f_inventory_informations_label.setFrameShadow(QFrame.Shadow.Raised)
        self._h_inventory_informations_label = QHBoxLayout(self._f_inventory_informations_label)
        self._h_inventory_informations_label.setObjectName(u"_h_inventory_informations_label")
        self._h_inventory_informations_label.setContentsMargins(5, 0, 0, 0)
        self._l_inventory_informations_product = QLabel(self._f_inventory_informations_label)
        self._l_inventory_informations_product.setObjectName(u"_l_inventory_informations_product")
        self._l_inventory_informations_product.setFont(self.font3)
        self._l_inventory_informations_product.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._l_inventory_informations_product.setWordWrap(True)
        self._h_inventory_informations_label.addWidget(self._l_inventory_informations_product)
        self._v_inventory_box_edit.addWidget(self._f_inventory_informations_label)
        self._v_inventory_input = QVBoxLayout()
        self._v_inventory_input.setSpacing(5)
        self._v_inventory_input.setObjectName(u"_v_inventory_input")
        self._l_inventory_name = QLabel(self._f_inventory_box_edit)
        self._l_inventory_name.setObjectName(u"_l_inventory_name")
        self._l_inventory_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._l_inventory_name)
        self._le_inventory_name = QLineEdit(self._f_inventory_box_edit)
        self._le_inventory_name.setObjectName(u"_le_inventory_name")
        self._le_inventory_name.setMinimumSize(QSize(0, 30))
        self._le_inventory_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._le_inventory_name)
        self._l__inventory_marque = QLabel(self._f_inventory_box_edit)
        self._l__inventory_marque.setObjectName(u"_l__inventory_marque")
        self._l__inventory_marque.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._l__inventory_marque)
        self._le_inventory_marque = QLineEdit(self._f_inventory_box_edit)
        self._le_inventory_marque.setObjectName(u"_le_inventory_marque")
        self._le_inventory_marque.setMinimumSize(QSize(0, 30))
        self._le_inventory_marque.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._le_inventory_marque)
        self._l_inventory_price = QLabel(self._f_inventory_box_edit)
        self._l_inventory_price.setObjectName(u"_l_inventory_price")
        self._l_inventory_price.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._l_inventory_price)
        self._ds_inventory_price = QDoubleSpinBox(self._f_inventory_box_edit)
        self._ds_inventory_price.setObjectName(u"_ds_inventory_price")
        self._ds_inventory_price.setMinimumSize(QSize(0, 30))
        self._ds_inventory_price.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._ds_inventory_price)
        self._l_inventory_quantity = QLabel(self._f_inventory_box_edit)
        self._l_inventory_quantity.setObjectName(u"_l_inventory_quantity")
        self._l_inventory_quantity.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._l_inventory_quantity)
        self._s_inventory_quantity = QSpinBox(self._f_inventory_box_edit)
        self._s_inventory_quantity.setObjectName(u"_s_inventory_quantity")
        self._s_inventory_quantity.setMinimumSize(QSize(0, 30))
        self._s_inventory_quantity.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._s_inventory_quantity)
        self._h_inventory_info_qty = QHBoxLayout()
        self._h_inventory_info_qty.setObjectName(u"_h_inventory_info_qty")
        self._cb_inventory_quantifiable = QCheckBox(self._f_inventory_box_edit)
        self._cb_inventory_quantifiable.setObjectName(u"_cb_inventory_quantifiable")
        self._h_inventory_info_qty.addWidget(self._cb_inventory_quantifiable)
        self._cb_inventory_location = QCheckBox(self._f_inventory_box_edit)
        self._cb_inventory_location.setObjectName(u"_cb_inventory_location")
        self._h_inventory_info_qty.addWidget(self._cb_inventory_location)
        self._v_inventory_input.addLayout(self._h_inventory_info_qty)
        self._l_inventory_type_remise = QLabel(self._f_inventory_box_edit)
        self._l_inventory_type_remise.setObjectName(u"_l_inventory_type_remise")
        self._l_inventory_type_remise.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._l_inventory_type_remise)
        self._cbx_inventory_type_remise = QComboBox(self._f_inventory_box_edit)
        self._cbx_inventory_type_remise.addItem(self.euro_icon, "")
        self._cbx_inventory_type_remise.addItem(self.pourcentage_icon, "")
        self._cbx_inventory_type_remise.setObjectName(u"_cbx_inventory_type_remise")
        self._cbx_inventory_type_remise.setMinimumSize(QSize(0, 30))
        self._v_inventory_input.addWidget(self._cbx_inventory_type_remise)
        self._l_inventory_date_fabric = QLabel(self._f_inventory_box_edit)
        self._l_inventory_date_fabric.setObjectName(u"_l_inventory_date_fabric")
        self._l_inventory_date_fabric.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._l_inventory_date_fabric)
        self._de_inventory_fabric = QDateEdit(self._f_inventory_box_edit)
        self._de_inventory_fabric.setObjectName(u"_de_inventory_fabric")
        self._de_inventory_fabric.setMinimumSize(QSize(0, 30))
        self._de_inventory_fabric.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._de_inventory_fabric)
        self._l_inventory_illustration_path = QLabel(self._f_inventory_box_edit)
        self._l_inventory_illustration_path.setObjectName(u"_l_inventory_illustration_path")
        self._l_inventory_illustration_path.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._l_inventory_illustration_path)
        self._h_inventory_illustration = QHBoxLayout()
        self._h_inventory_illustration.setObjectName(u"_h_inventory_illustration")
        self._le_inventory_illustration_path = QLineEdit(self._f_inventory_box_edit)
        self._le_inventory_illustration_path.setObjectName(u"_le_inventory_illustration_path")
        self._le_inventory_illustration_path.setMinimumSize(QSize(0, 30))
        self._le_inventory_illustration_path.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._h_inventory_illustration.addWidget(self._le_inventory_illustration_path)
        self._tb_inventory_illustration_path = QToolButton(self._f_inventory_box_edit)
        self._tb_inventory_illustration_path.setObjectName(u"_tb_inventory_illustration_path")
        self._tb_inventory_illustration_path.setMinimumSize(QSize(0, 30))
        self._h_inventory_illustration.addWidget(self._tb_inventory_illustration_path)
        self._v_inventory_input.addLayout(self._h_inventory_illustration)
        self._l_inventory_import_path = QLabel(self._f_inventory_box_edit)
        self._l_inventory_import_path.setObjectName(u"_l_inventory_import_path")
        self._l_inventory_import_path.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._v_inventory_input.addWidget(self._l_inventory_import_path)
        self._h_inventory_import_path = QHBoxLayout()
        self._h_inventory_import_path.setObjectName(u"_h_inventory_import_path")
        self._le_inventory_import_path = QLineEdit(self._f_inventory_box_edit)
        self._le_inventory_import_path.setObjectName(u"_le_inventory_import_path")
        self._le_inventory_import_path.setMinimumSize(QSize(0, 30))
        self._le_inventory_import_path.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._h_inventory_import_path.addWidget(self._le_inventory_import_path)
        self._tb_inventory_import_path = QToolButton(self._f_inventory_box_edit)
        self._tb_inventory_import_path.setObjectName(u"_tb_inventory_import_path")
        self._tb_inventory_import_path.setMinimumSize(QSize(0, 30))
        self._h_inventory_import_path.addWidget(self._tb_inventory_import_path)
        self._v_inventory_input.addLayout(self._h_inventory_import_path)
        self._v_inventory_box_edit.addLayout(self._v_inventory_input)
        self._h_inventory_box_bottom = QHBoxLayout()
        self._h_inventory_box_bottom.setObjectName(u"_h_inventory_box_bottom")
        self._b_inventory_add = QPushButton(self._f_inventory_box_edit)
        self._b_inventory_add.setObjectName(u"_b_inventory_add")
        self._b_inventory_add.setIcon(self.plus_icon)
        self._b_inventory_add.setFlat(True)
        self._h_inventory_box_bottom.addWidget(self._b_inventory_add)
        self._b_inventory_achat = QPushButton(self._f_inventory_box_edit)
        self._b_inventory_achat.setObjectName(u"_b_inventory_achat")
        self._b_inventory_achat.setIcon(self.achat_icon)
        self._b_inventory_achat.setFlat(True)
        self._h_inventory_box_bottom.addWidget(self._b_inventory_achat)
        self._b_inventory_update = QPushButton(self._f_inventory_box_edit)
        self._b_inventory_update.setObjectName(u"_b_inventory_update")
        self._b_inventory_update.setIcon(self.mise_a_jour_icon)
        self._b_inventory_update.setFlat(True)
        self._h_inventory_box_bottom.addWidget(self._b_inventory_update)
        self._b_inventory_delete = QPushButton(self._f_inventory_box_edit)
        self._b_inventory_delete.setObjectName(u"_b_inventory_delete")
        self._b_inventory_delete.setIcon(self.corbeil_icon)
        self._b_inventory_delete.setFlat(True)
        self._h_inventory_box_bottom.addWidget(self._b_inventory_delete)
        self._v_inventory_box_edit.addLayout(self._h_inventory_box_bottom)
        self._g_inventory.addWidget(self._f_inventory_box_edit, 1, 3, 2, 1, Qt.AlignVCenter)
        self._ccw_inventory_sum_sold = CustomCardWidget([244, 162, 97, 1], self)
        self._ccw_inventory_sum_sold.setObjectName(u"_ccw_inventory_sum_sold")
        self._ccw_inventory_sum_sold.setMinimumSize(QSize(0, 70))
        self._ccw_inventory_sum_sold.setMaximumSize(QSize(16777215, 70))
        self._g_inventory_sum_sold = QGridLayout(self._ccw_inventory_sum_sold)
        self._g_inventory_sum_sold.setObjectName(u"_g_inventory_sum_sold")
        self._l_inventory_sum_sold_value = QLabel(self._ccw_inventory_sum_sold)
        self._l_inventory_sum_sold_value.setObjectName(u"_l_inventory_sum_sold_value")
        self._l_inventory_sum_sold_value.setFont(self.font9)
        self._g_inventory_sum_sold.addWidget(self._l_inventory_sum_sold_value, 0, 1, 1, 1)
        self._l_inventory_sum_sold = QLabel(self._ccw_inventory_sum_sold)
        self._l_inventory_sum_sold.setObjectName(u"_l_inventory_sum_sold")
        self._g_inventory_sum_sold.addWidget(self._l_inventory_sum_sold, 1, 1, 1, 1)
        self._l_inventory_icon_sum_sold = QLabel(self._ccw_inventory_sum_sold)
        self._l_inventory_icon_sum_sold.setObjectName(u"_l_inventory_icon_sum_sold")
        self._l_inventory_icon_sum_sold.setMinimumSize(QSize(45, 45))
        self._l_inventory_icon_sum_sold.setMaximumSize(QSize(45, 45))
        self._l_inventory_icon_sum_sold.setPixmap(self.total_vente_pixmap)
        self._l_inventory_icon_sum_sold.setScaledContents(True)
        self._g_inventory_sum_sold.addWidget(self._l_inventory_icon_sum_sold, 0, 0, 2, 1)
        self._g_inventory.addWidget(self._ccw_inventory_sum_sold, 2, 2, 1, 1)
        self._ccw_inventory_low_sale = CustomCardWidget([233, 196, 106, 1], self)
        self._ccw_inventory_low_sale.setObjectName(u"_ccw_inventory_low_sale")
        self._ccw_inventory_low_sale.setMinimumSize(QSize(0, 70))
        self._ccw_inventory_low_sale.setMaximumSize(QSize(16777215, 70))
        self._g_inventory_low_sale = QGridLayout(self._ccw_inventory_low_sale)
        self._g_inventory_low_sale.setObjectName(u"_g_inventory_low_sale")
        self._l_inventory_low_sale_value = QLabel(self._ccw_inventory_low_sale)
        self._l_inventory_low_sale_value.setObjectName(u"_l_inventory_low_sale_value")
        self._l_inventory_low_sale_value.setFont(self.font9)
        self._g_inventory_low_sale.addWidget(self._l_inventory_low_sale_value, 0, 1, 1, 1)
        self._l_inventory_low_sale = QLabel(self._ccw_inventory_low_sale)
        self._l_inventory_low_sale.setObjectName(u"_l_inventory_low_sale")
        self._g_inventory_low_sale.addWidget(self._l_inventory_low_sale, 1, 1, 1, 1)
        self._l_inventory_icon_low_sale = QLabel(self._ccw_inventory_low_sale)
        self._l_inventory_icon_low_sale.setObjectName(u"_l_inventory_icon_low_sale")
        self._l_inventory_icon_low_sale.setMinimumSize(QSize(45, 45))
        self._l_inventory_icon_low_sale.setMaximumSize(QSize(45, 45))
        self._l_inventory_icon_low_sale.setPixmap(self.moins_vendu_pixmap)
        self._l_inventory_icon_low_sale.setScaledContents(True)
        self._g_inventory_low_sale.addWidget(self._l_inventory_icon_low_sale, 0, 0, 2, 1)
        self._g_inventory.addWidget(self._ccw_inventory_low_sale, 2, 1, 1, 1)
        self._sw_main_dialog.addWidget(self._p_inventory)
