{
    "entrepriseLine": "nom",
    "entrepreneurLine": "patron",
    "rueLine": "adresse",
    "villeLine": "ville",
    "communeLine": "commune",
    "cpLine": "code_postal",
    "departementLine": "departement",
    "mailLine": "mail",
    "numeroLine": "telephone",
    "siretLine": "siret",
    "sirenLine": "siren",
    "apeLine": "code_ape",
    "ibanLine": "iban",
    "bicLine": "bic",
    "capitalLine": "capital",
}